services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    restart: unless-stopped
    volumes:
      - /home/misc/jellyfin/config:/config
      - /home/misc/jellyfin/cache:/cache
      - /home/misc/jellyfin/media:/media
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/jellyfin.svg

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - 9696:9696
    restart: unless-stopped  
    volumes:
      - /home/misc/jellyfin/prowlarr/config:/config
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/prowlarr.svg

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /home/misc/jellyfin/radarr/config:/config
      - /home/misc/jellyfin/radarr/data:/data
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/radarr.svg

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /home/misc/jellyfin/sonarr/config:/config
      - /home/misc/jellyfin/sonarr/data:/data
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/sonarr.svg

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - 8087:8087
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /home/misc/jellyfin/qbittorrent/config:/config
      - /home/misc/jellyfin/qbittorrent/data:/data
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/qbittorrent.svg

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    ports:
      - 5055:5055
    restart: unless-stopped
    volumes:
      - /home/misc/jellyfin/seerr/config:/app/config
    healthcheck:
      test:
        - CMD-SHELL
        - "wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1"
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/seerr.svg