services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096/tcp
      - 7359:7359/udp
    volumes:
      - /home/misc/jellyfin/config:/config
      - /home/misc/jellyfin/cache:/cache
      - /home/misc/jellyfin/media:/media
    restart: unless-stopped
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/jellyfin.svg
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /home/misc/jellyfin/radarr/config:/config
      - /home/misc/jellyfin/radarr/movies:/movies
      - /home/misc/jellyfin/radarr/downloads:/downloads
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/radarr.svg
  
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /home/misc/jellyfin/sonarr/config:/config
      - /home/misc/jellyfin/sonarr/tv:/tv
      - /home/misc/jellyfin/sonarr/downloads:/downloads
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/sonarr.svg

  seerr:
    image: ghcr.io/seerr-team/seerr:latest
    container_name: seerr
    ports:
      - 5055:5055
    volumes:
      - /home/misc/jellyfin/seerr:/app/config
    labels:
      com.getarcaneapp.arcane.icon: https://cdn.jsdelivr.net/gh/selfhst/icons@main/svg/seerr.svg
    environment:
      - LOG_LEVEL=debug
      - PORT=5055
    restart: unless-stopped
    init: true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public
        || exit 1
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges